#!/usr/bin/env python3
"""Generate operator skeleton files from a SPEC.yaml."""

import os
import sys
import yaml
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parent.parent
OPS_DIR = PROJECT_ROOT / "ops"
TESTS_DIR = PROJECT_ROOT / "tests"
DOCS_DIR = PROJECT_ROOT / "docs" / "operators"
HARNESS_OPS_DIR = PROJECT_ROOT / ".npu-harness" / "operators"

GENERATED_MARKER = "// AUTO-GENERATED by generate_op_from_spec.py. Edit with care."


def load_spec(spec_path):
    with open(spec_path, 'r') as f:
        return yaml.safe_load(f)


def mkdir_p(path):
    os.makedirs(path, exist_ok=True)


def write_if_not_exists(path, content, force=False):
    """Write file if it doesn't exist or force=True. Returns True if written."""
    if os.path.exists(path) and not force:
        print(f"  SKIP (exists): {path}")
        return False
    with open(path, 'w') as f:
        f.write(content)
    print(f"  WRITE: {path}")
    return True


def generate_operator(spec_path, force=False):
    spec = load_spec(spec_path)
    name = spec["name"]
    category = spec.get("category", "custom")

    print(f"\nGenerating operator: {name} (category: {category})")

    op_dir = OPS_DIR / name

    # Create directory structure
    for sub in ["kernel", "host", "runner", "golden", "bench"]:
        mkdir_p(op_dir / sub)
    mkdir_p(HARNESS_OPS_DIR / name)

    # --- SPEC.yaml in harness ---
    harness_spec = HARNESS_OPS_DIR / name / "SPEC.yaml"
    with open(harness_spec, 'w') as f:
        yaml.dump(spec, f, default_flow_style=False, sort_keys=False)
    print(f"  WRITE: {harness_spec}")

    # --- CMakeLists.txt ---
    cmake_content = f'''{GENERATED_MARKER}
# CMakeLists.txt for {name}

set(OP_DIR ${{CMAKE_CURRENT_SOURCE_DIR}})

# Golden sources (always built)
set(GOLDEN_SOURCES
    golden/{name}_golden.hpp
    golden/{name}_golden.cpp
)

# Host tiling sources
set(HOST_SOURCES
    host/{name}_tiling.hpp
    host/{name}_tiling.cpp
)

# Runner sources
set(RUNNER_SOURCES
    runner/{name}_runner.hpp
    runner/{name}_runner.cpp
)

# Kernel sources (only with Ascend)
set(KERNEL_SOURCES
    kernel/{name}_kernel.cpp
)

harness_add_operator({name}
    HAS_KERNEL
    HAS_BENCHMARK
    GOLDEN_SOURCES ${{GOLDEN_SOURCES}}
    HOST_SOURCES ${{HOST_SOURCES}}
    RUNNER_SOURCES ${{RUNNER_SOURCES}}
    KERNEL_SOURCES ${{KERNEL_SOURCES}}
    BENCH_SOURCES bench/bench_{name}.cpp
)
'''
    write_if_not_exists(op_dir / "CMakeLists.txt", cmake_content, force)

    # --- Golden header ---
    dtypes = spec.get("inputs", [{}])[0].get("dtype", ["float32"])
    dtype_str = ", ".join(str(d) for d in dtypes)
    golden_hdr = f'''{GENERATED_MARKER}
#pragma once
#include <vector>
#include <cstddef>
#include "harness/tensor.hpp"
#include "harness/shape.hpp"

namespace ops {{
namespace {name} {{

void cpu_golden(
    const float* input,
    float* output,
    const harness::Shape& shape);

}}  // namespace {name}
}}  // namespace ops
'''
    write_if_not_exists(op_dir / "golden" / f"{name}_golden.hpp", golden_hdr, force)

    # --- Golden impl ---
    golden_cpp = f'''{GENERATED_MARKER}
#include "{name}_golden.hpp"
#include <cmath>
#include <algorithm>

namespace ops {{
namespace {name} {{

void cpu_golden(
    const float* input,
    float* output,
    const harness::Shape& shape)
{{
    // TODO: Implement CPU golden for {name}
    // Category: {category}
    // Dtypes: {dtype_str}
    size_t n = shape.num_elements();
    // Placeholder: copy input to output
    for (size_t i = 0; i < n; ++i) {{
        output[i] = input[i];
    }}
}}

}}  // namespace {name}
}}  // namespace ops
'''
    write_if_not_exists(op_dir / "golden" / f"{name}_golden.cpp", golden_cpp, force)

    # --- Tiling header ---
    tiling_hdr = f'''{GENERATED_MARKER}
#pragma once
#include <cstddef>
#include <cstdint>
#include "harness/shape.hpp"

namespace ops {{
namespace {name} {{

struct TilingConfig {{
    size_t tile_size = 256;
    size_t block_dim = 32;
    size_t num_blocks = 0;
    size_t tail_size = 0;

    void compute(const harness::Shape& shape);
}};

}}  // namespace {name}
}}  // namespace ops
'''
    write_if_not_exists(op_dir / "host" / f"{name}_tiling.hpp", tiling_hdr, force)

    # --- Tiling impl ---
    tiling_cpp = f'''{GENERATED_MARKER}
#include "{name}_tiling.hpp"

namespace ops {{
namespace {name} {{

void TilingConfig::compute(const harness::Shape& shape) {{
    size_t n = shape.num_elements();
    num_blocks = (n + tile_size - 1) / tile_size;
    tail_size = n % tile_size;
    if (tail_size == 0) tail_size = tile_size;
}}

}}  // namespace {name}
}}  // namespace ops
'''
    write_if_not_exists(op_dir / "host" / f"{name}_tiling.cpp", tiling_cpp, force)

    # --- Runner header ---
    runner_hdr = f'''{GENERATED_MARKER}
#pragma once
#include <cstddef>
#include "harness/tensor.hpp"
#include "harness/shape.hpp"
#include "{name}_tiling.hpp"

namespace ops {{
namespace {name} {{

class Runner {{
public:
    Runner() = default;

    void run(
        const float* input,
        float* output,
        const harness::Shape& shape);

private:
    TilingConfig tiling_;
}};

}}  // namespace {name}
}}  // namespace ops
'''
    write_if_not_exists(op_dir / "runner" / f"{name}_runner.hpp", runner_hdr, force)

    # --- Runner impl ---
    runner_cpp = f'''{GENERATED_MARKER}
#include "{name}_runner.hpp"
#include "{name}_golden.hpp"
#include "harness/logging.hpp"
#include "harness/skip.hpp"

namespace ops {{
namespace {name} {{

void Runner::run(
    const float* input,
    float* output,
    const harness::Shape& shape)
{{
    tiling_.compute(shape);

#if defined(HARNESS_HAS_ASCEND) && HARNESS_HAS_ASCEND == 1
    if (harness::IsAscendRuntimeAvailable() && harness::HasUsableDevice()) {{
        // TODO: NPU launch path
        harness::logging::info("Runner: NPU launch for {name}");
        // kernel<<<blocks, stream>>>(...);
    }} else {{
        harness::logging::info("Runner: falling back to CPU golden (no NPU)");
        cpu_golden(input, output, shape);
    }}
#else
    harness::logging::info("Runner: CPU golden (host-only build)");
    cpu_golden(input, output, shape);
#endif
}}

}}  // namespace {name}
}}  // namespace ops
'''
    write_if_not_exists(op_dir / "runner" / f"{name}_runner.cpp", runner_cpp, force)

    # --- Kernel ---
    kernel_cpp = f'''{GENERATED_MARKER}
// Ascend C kernel for {name}
// Target arch: dav-2201

#if defined(HARNESS_HAS_ASCEND) && HARNESS_HAS_ASCEND == 1

#include "kernel_operator.h"

extern "C" __global__ __aicore__
void {name}_kernel(
    __gm__ float* input,
    __gm__ float* output,
    int64_t num_elements)
{{
    // TODO: Implement Ascend C kernel for {name}
    int64_t idx = get_block_idx_x() * get_block_dim_x() + get_thread_idx_x();
    if (idx < num_elements) {{
        output[idx] = input[idx];  // placeholder: elementwise copy
    }}
}}

#endif  // HARNESS_HAS_ASCEND
'''
    write_if_not_exists(op_dir / "kernel" / f"{name}_kernel.cpp", kernel_cpp, force)

    # --- Benchmark ---
    bench_cpp = f'''{GENERATED_MARKER}
// Benchmark for {name}
#include <iostream>
#include <chrono>
#include <vector>
#include "{name}_runner.hpp"
#include "harness/test_utils.hpp"
#include "harness/shape.hpp"

int main() {{
    std::cout << "Benchmark: {name}" << std::endl;
    harness::Shape shape({{1024}});
    size_t n = shape.num_elements();

    auto input = harness::test::generate_random_float(n);
    std::vector<float> output(n);

    ops::{name}::Runner runner;

    // Warmup
    for (int i = 0; i < 10; ++i) {{
        runner.run(input.data(), output.data(), shape);
    }}

    // Measure
    auto start = std::chrono::high_resolution_clock::now();
    for (int i = 0; i < 100; ++i) {{
        runner.run(input.data(), output.data(), shape);
    }}
    auto end = std::chrono::high_resolution_clock::now();

    double avg_us = std::chrono::duration<double, std::micro>(end - start).count() / 100.0;
    std::cout << "  avg=" << avg_us << " us" << std::endl;
    std::cout << "  shape=" << shape.to_string() << std::endl;
    return 0;
}}
'''
    write_if_not_exists(op_dir / "bench" / f"bench_{name}.cpp", bench_cpp, force)

    # --- Test file ---
    test_inputs = spec.get("inputs", [])
    test_cpp = f'''{GENERATED_MARKER}
// GTest for {name}
#include <gtest/gtest.h>
#include <vector>
#include <cmath>
#include "harness/accuracy.hpp"
#include "harness/test_utils.hpp"
#include "harness/shape.hpp"
#include "harness/skip.hpp"

// Include operator golden
#include "{name}_golden.hpp"
#include "{name}_runner.hpp"

class {name.capitalize()}_Test : public ::testing::Test {{
protected:
    void SetUp() override {{
        seed_ = 20260522;
    }}
    uint64_t seed_;
}};

TEST_F({name.capitalize()}_Test, Golden_BasicShape) {{
    harness::Shape shape({{1024}});
    size_t n = shape.num_elements();

    auto input = harness::test::generate_random_float(n, seed_);
    std::vector<float> golden_out(n);
    std::vector<float> runner_out(n);

    ops::{name}::cpu_golden(input.data(), golden_out.data(), shape);

    ops::{name}::Runner runner;
    runner.run(input.data(), runner_out.data(), shape);

    auto report = harness::accuracy::CompareArrays(golden_out, runner_out,
        harness::accuracy::Tolerance{{1e-5, 1e-5}});
    EXPECT_TRUE(report.passed) << report.ToString();
}}

TEST_F({name.capitalize()}_Test, Golden_SmallShape) {{
    harness::Shape shape({{1}});
    size_t n = shape.num_elements();
    std::vector<float> input = {{3.14f}};
    std::vector<float> golden_out(n);
    std::vector<float> runner_out(n);

    ops::{name}::cpu_golden(input.data(), golden_out.data(), shape);

    ops::{name}::Runner runner;
    runner.run(input.data(), runner_out.data(), shape);

    auto report = harness::accuracy::CompareArrays(golden_out, runner_out,
        harness::accuracy::Tolerance{{1e-5, 1e-5}});
    EXPECT_TRUE(report.passed) << report.ToString();
}}
'''
    test_path = TESTS_DIR / f"test_{name}.cpp"
    write_if_not_exists(test_path, test_cpp, force)

    # --- Operator doc ---
    doc_content = f'''# {name}

Generated from SPEC.yaml.

## Category
{category}

## Dtypes
{dtype_str}

## Architecture
Target: dav-2201

## Files
- `ops/{name}/golden/` — CPU golden reference
- `ops/{name}/kernel/` — Ascend C kernel
- `ops/{name}/host/` — Tiling and host-side logic
- `ops/{name}/runner/` — Runner with NPU/CPU dispatch
- `tests/test_{name}.cpp` — GTest tests
- `ops/{name}/bench/` — Benchmark
'''
    write_if_not_exists(DOCS_DIR / f"{name}.md", doc_content, force)

    # --- Harness STATUS.md ---
    status_content = f'''# {name} — Status

- Generated: {timestamp()}
- Built (host): pending
- Tested (host): pending
- Built (NPU): pending
- Tested (NPU): pending
- Accuracy: pending
- Performance: pending
'''
    write_if_not_exists(HARNESS_OPS_DIR / name / "STATUS.md", status_content, force)

    # --- Harness PLAN.md ---
    plan_content = f'''# {name} — Implementation Plan

## Steps
1. [ ] Complete CPU golden implementation
2. [ ] Complete tiling design
3. [ ] Implement Ascend C kernel
4. [ ] Complete runner integration
5. [ ] Add comprehensive GTest coverage
6. [ ] Host build and test
7. [ ] NPU build and test (if available)
8. [ ] Benchmark (if applicable)

## Files
- ops/{name}/golden/{name}_golden.cpp
- ops/{name}/host/{name}_tiling.cpp
- ops/{name}/kernel/{name}_kernel.cpp
- ops/{name}/runner/{name}_runner.cpp
- tests/test_{name}.cpp
'''
    write_if_not_exists(HARNESS_OPS_DIR / name / "PLAN.md", plan_content, force)

    # --- Update registry ---
    update_registry(name, spec)

    print(f"\nOperator {name} generated successfully.")
    print(f"Next steps:")
    print(f"  1. Complete ops/{name}/golden/{name}_golden.cpp")
    print(f"  2. Complete ops/{name}/kernel/{name}_kernel.cpp")
    print(f"  3. Run: python3 scripts/harness.py build --mode host")
    print(f"  4. Run: python3 scripts/harness.py test --mode host --op {name}")


def update_registry(name, spec):
    registry_path = PROJECT_ROOT / "OPERATOR_REGISTRY.yaml"
    if registry_path.exists():
        with open(registry_path, 'r') as f:
            registry = yaml.safe_load(f)
    else:
        registry = {"schema_version": 1, "target_arch_default": "dav-2201", "operators": {}}

    if "operators" not in registry:
        registry["operators"] = {}

    if name not in registry["operators"]:
        registry["operators"][name] = {}

    registry["operators"][name].update({
        "spec": f"specs/{name}.yaml",
        "status_file": f".npu-harness/operators/{name}/STATUS.md",
        "category": spec.get("category", "custom"),
        "generated": True,
        "generated_at": timestamp(),
        "built_host": False,
        "tested_host": False,
        "built_npu": False,
        "tested_npu": "pending",
        "npu_skip_reason": "",
        "accuracy": "pending",
        "performance": "pending",
    })

    with open(registry_path, 'w') as f:
        yaml.dump(registry, f, default_flow_style=False, sort_keys=False)
    print(f"  Updated: {registry_path}")


def timestamp():
    from datetime import datetime
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")


def main():
    if len(sys.argv) < 2:
        print("Usage: python3 generate_op_from_spec.py <spec.yaml> [--force]")
        print("  Generates operator skeleton files from a spec YAML.")
        sys.exit(1)

    spec_path = sys.argv[1]
    force = "--force" in sys.argv

    if not os.path.exists(spec_path):
        print(f"Spec file not found: {spec_path}")
        sys.exit(1)

    generate_operator(spec_path, force)


if __name__ == "__main__":
    main()
